version: '3.9'
services:
  postgres-bookingdb:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_service
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis_booking
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - proselyte-redis-net
  redis-insight:
    image: redis/redisinsight:latest
    container_name: redisinsight-booking
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - proselyte-redis-net
volumes:
  pgdata:
  redis-insight:
networks:
  proselyte-redis-net:
    driver: bridge
